### ISSUE TITLE
Assembler not assembling (1.7.10-0.8)

### ISSUE THREAD

**Issue by zane49er2** [Mordenkainen/EquivalentEnergistics#118]
When I choose a recipe, it shows on the crafting CPU and the middle of the assembler, but the assembler's border turns red and doesn't craft.
I have plenty of EMC and power in the system, and have tried this with small vanilla items like arrows.
Pressing cancel on the processor also does not cancel the assembler.

**Comment by Mordenkainen** [comment]
Do you have WAILA installed? If so, what does WAILA say when you look at the assembler?

How much power and EMC is plenty?

Do you have standard AE storage cells with enough room to store whatever you are crafting?

The behavior you describe is the Assembler telling you it is missing something needed to complete the crafting. AE itself pretty much ensures you have enough EMC, so that usually means:
1. You dont have enough power.
2. You do not have any place to store the finished product.
3. You don't have any place to store any "left over" EMC from the crafting.

Canceling the job not clearing the assembler is normal AE behavior. It cancels further action on the job, but not any crafting tasks that have already been started.

**Comment by zane49er2** [comment]
WAILA does not give a message when I look at the assembler.
Billions of EMC, and a creative cell.
I think it was that I didn't have space for the product. After adding more storage cells, the system is working fine. Sorry for wasting your time.
Thank you for that information, I wan't aware.

**Comment by Mordenkainen** [comment]
No problem!
