### ISSUE TITLE
Bug/Issue - EMC Condensers accept items that do not have an EMC value

### ISSUE THREAD

**Issue by lrwerewolf** [Mordenkainen/EquivalentEnergistics#131]
Summary:
Condensers will accept up to four stacks of items with no EMC value, which clogs the condenser until the items are somehow removed.

Setup (image attached below):
Setup #1 A network which has an unconfigured storage bus connected to an Ultimate EMC Condenser, with an amount of EMC storage but no item storage.  Items are inserted into the network either by an interface or by a terminal.
Setup #2 The same network as above, but instead of injecting items via terminal or interface, items are injected via conduit/duct/hopper directly into ultimate EMC condenser.

What happens:
-- With item stacks having an EMC value: item stack enters condenser and is converted to network EMC.
-- With item stacks that have no EMC value: up to four stacks of items are pushed into the condenser and become stuck there, blocking the condenser from accepting any further items for breakdown.

What user expects:
Items with no EMC value should not be accepted into the EMC Condenser regardless of how they are presented to the condenser

Versions of relevant mods:
appliedenergistics2-rv5-stable-011.jar
EquivalentEnergistics-1.12.2-PE_1.3.1B-AE2_RV5-0.8.3.jar

Image:
![image](https://user-images.githubusercontent.com/5785242/47128583-1288ba80-d24f-11e8-8aca-553c491d6f20.png)

**Comment by Mordenkainen** [comment]
This is the expected behavior. The first two tiers of condensers will only accept items with EMC, the top two tiers accept any items, convert items with EMC, and ejects items with no EMC into the AE network or an adjacent inventory. This allows the higher tier condensers to be used to "sort" items with EMC from those that do not.

Either provide a place where unconvertable items can go, or use hoppers/pipes to extract the "stuck" items. You can detect when the condenser is stuck using a redstone comparator placed next to the condenser.

Higher tier condensers have more features. This happens to be one of them.

**Comment by lrwerewolf** [comment]
Good info to know, thank you.
