### ISSUE TITLE
Items with subitems condense using the EMC value of the subitem with damage value 0

### ISSUE THREAD

**Issue by RoloEdits** [Mordenkainen/EquivalentEnergistics#3]
When Piping Octuple Compressed Cobblestone In It Gives No EMC Back Just Eats It Up.

**Comment by Mordenkainen** [comment]
The Condenser consumes power in relation to the EMC of the items it is converting.

Octuple Compressed cobble is worth 43,046,721 EMC. With the default config settings for power this will cost 430,468 AE per block. It is unlikely your network can provide this much power unless you have a bunch of AE Energy Cells attached (that much power is more then 2 full energy cells!).

Some suggestions:
1. Add Energy cells... Lots of them.
2. Reduce the cost per EMC in the config file. Default is 0.01. You can set this to 0 to remove the power requirement entirely, or set it to something like 0.00001 to reduce the cost. (Its the "PowerDrainPerEMCCondensed" line in the config)

It looks like its "eating" the blocks because it can hold 4 stacks internally before it stops accepting items.

**Comment by RoloEdits** [comment]
Thank You For Your Help

**Comment by RoloEdits** [comment]
hmm it still seems to not work even after setting the value to 0 and surrounding it with creative energy cells  on all sides and its not just octuple compressed but also singularities from ae2 with a value of 256,000 and its using emc but not all of it i put 10 in so that should give me 10000 crystals  but its not

**Comment by RoloEdits** [comment]
put in 10 singularities got 10 crystals 1000:1 ratio. should also mention i changed "I:CrystalsProducedPerTick=10000" to see if the condenser wasn't able to keep up with the production. similar to the transmutation tablet were if your inventories full and it will just eat up EMC anyways even if your not gonna get anything

**Comment by Mordenkainen** [comment]
Can you post your EquivalentEnergistics config, as well as the versions of AE2, EE3, ExtraUtilities, and Forge? I am not able to recreate any of these problems.

A 256,000 EMC item gave me 1000 crystals, and Octuple Compressed Cobble is breaking down fine for me as long as I make the required power available.

**Comment by RoloEdits** [comment]
# Configuration file

condenser {
    I:CrystalsProducedPerTick=10000
    I:IdlePowerDrain=0
    I:ItemsCondensedPerTick=8
    D:PowerDrainPerEMCCondensed=0
}


crafter {
    I:IdlePowerDrain=0
    D:PowerDrainPerCraftingTick=1.5
    I:TicksPerCrafting=20
}


general {
    I:CrystalEMC=256
}

**Comment by RoloEdits** [comment]
appliedenergistics2-rv2-stable-9

EquivalentExchange3-1.7.10-0.3.507

extrautilities-1.2.6

1.7.10-Forge10.13.4.1472-1.7.10

**Comment by Mordenkainen** [comment]
Thanks for the info. I see from your other issue that you also have a mod that adds EMC values to AE2 items.

I will set up a test with all of these mods and see if I can recreate the issue. If I can not, I may have to have you send me your mudpack and world so I can see if I can figure out why it's not working.

**Comment by RoloEdits** [comment]
Ok

**Comment by Mordenkainen** [comment]
I am unable to recreate this issue.

Please try the following test in creative mode to see if it works:
Build a new AE network with the following components:
- Terminal
- Drive or ME Chest.
- Creative Energy Cell
- 2 64k Storage Cells
- EMC Condenser with Hopper

Put octuple compressed cobble in the hopper, see that EMC Crystals are generated. When complete, multiply the number of EMC Crystals generated by 256. This should be approximately the EMC value of the octuple compressed cobble. This number may be up to 255 EMC lower than the actual value of the cobble, this is normal for items not evenly divisible by 256. With default EMC values this should be 168,151 EMC Crystals.

Repeat this test with the Singularity. You should get 1000 EMC Crystals.

If these tests work, then I believe your problem is 1 of two issues:
1. Your AE network does not have enough power. Add ME Energy Cells/Dense Energy Cells to your network.
2. The condenser can't find a place to put the crystals. Make sure you have ample storage space.

**Comment by RoloEdits** [comment]
I Have Tried And They Have Produced The Same Results As Before ie A Singularity Is A 1000th The Value and only Producing 1 Crystal And After Putting 256 Octuple Compressed in i Got 9 Crystals Out

This Is My Setup For Both 

![2015-06-29_16 57 02](https://cloud.githubusercontent.com/assets/12489689/8421268/3e20647a-1e81-11e5-9400-7122978774c0.png)

![2015-06-29_16 57 09](https://cloud.githubusercontent.com/assets/12489689/8421281/5b494738-1e81-11e5-9307-89e589432cce.png)

![2015-06-29_16 57 30](https://cloud.githubusercontent.com/assets/12489689/8421288/6b005176-1e81-11e5-8084-2ac285a0142c.png)

Put One In Got Nothing Back

![2015-06-29_16 57 41](https://cloud.githubusercontent.com/assets/12489689/8421300/81550f8e-1e81-11e5-9f05-753701b15b8f.png)

Tried Putting hopper On The Side

![2015-06-29_16 58 02](https://cloud.githubusercontent.com/assets/12489689/8421308/9172f8a4-1e81-11e5-80fb-6e0968537093.png)

Same Result Got Nothing Back

![2015-06-29_16 58 13](https://cloud.githubusercontent.com/assets/12489689/8421314/a1431bc4-1e81-11e5-9bd5-986df197e036.png)

Next up Singularities

![2015-06-29_17 00 27](https://cloud.githubusercontent.com/assets/12489689/8421327/b66a312c-1e81-11e5-8c73-9cbf473d6505.png)

Got One Back

![2015-06-29_17 00 39](https://cloud.githubusercontent.com/assets/12489689/8421334/c44e1b78-1e81-11e5-9fbb-625d8d677caa.png)

And After Putting 256 Octuple Compressed Thinking It Was Taking The Value As One Like Normal Cobble I Got 9 Back

![2015-06-29_17 06 20](https://cloud.githubusercontent.com/assets/12489689/8421348/f320abd2-1e81-11e5-9c33-a2472f31effd.png)

**Comment by RoloEdits** [comment]
And This Was The Config Settings During Testing 

# Configuration file

condenser {
    I:CrystalsProducedPerTick=10000
    I:IdlePowerDrain=0
    I:ItemsCondensedPerTick=8
    D:PowerDrainPerEMCCondensed=0
}


crafter {
    I:IdlePowerDrain=0
    D:PowerDrainPerCraftingTick=1.5
    I:TicksPerCrafting=20
}


general {
    I:CrystalEMC=256
}

**Comment by Mordenkainen** [comment]
Ok, I'm stumped.

Can you provide me your modpack via dropbox or something?

**Comment by RoloEdits** [comment]
Yes Its Pretty Big Tho So It Will Take A Minute. Want Me To Give You The Configs And Mods Folder As Well As The Testing World?

**Comment by Mordenkainen** [comment]
if you can that would be wonderful.

**Comment by RoloEdits** [comment]
Ok Let Me Get Started Doing That

**Comment by RoloEdits** [comment]
https://www.dropbox.com/s/a8jqlqt5bq9bmt7/EE%20Testing.rar?dl=0  

Hope This Works

If You Need Anything Else Don't Hesitate To Ask

**Comment by Mordenkainen** [comment]
ok, got it, feel free to delete it if you need to free up some space.

Looking at it now.

**Comment by RoloEdits** [comment]
OK

**Comment by Mordenkainen** [comment]
Debugging now, it did recreate the issue. Still don't know why though.

Boy that is a lot of mods!

**Comment by RoloEdits** [comment]
Great

and yeah to keep from getting bored I find new mods to keep entertained

**Comment by Mordenkainen** [comment]
GRRRRR! Stupid Dev!!!!

I couldn't recreate the issue BECAUSE I HAD ALREADY FIXED IT! DUH!

It will be fixed in the new release, which should be ready in the next couple of days.

**Comment by RoloEdits** [comment]
hahahahhahahaha i had a similar moment yesterday when i was referencing information that had already been calculated and was  wondering why it wasn't updating with new info

**Comment by RoloEdits** [comment]
thanks for your help btw
