### ISSUE TITLE
[Suggestion] Transmutation Terminal

### ISSUE THREAD

**Issue by Silly511** [Mordenkainen/EquivalentEnergistics#35]
I think you should add a transmutation terminal that would be just like the transmutation tablet except that instead of displaying the player's EMC it would display the total EMC of all the items in the network.

**Comment by MaPePeR** [comment]
A "sort by emc"-option would also be nice, if you didn't already did that.

**Comment by Mordenkainen** [comment]
Hmm, I'm not quite sure where I would go with this.

I wouldn't use the total EMC of all values in storage, since I do not want to be responsible for figuring out an algorithm to try to "guess" what the user wants me to convert to EMC for the transmutation.

The terminal would also need to show the user looking at it only the transmutations they have learned, and if they are doing things in the terminal then there may be some issues to worry about if multiple users are using it at the same time.

I haven't worked with multipart yet, and all the terminals are multipart parts.

And finally, I hate building GUI's.

But all that said, I'll leave it open and see where it goes.

**Comment by Anyone700** [comment]
A much easier way of doing this is only showing patterns known by the network. You could add a pattern storage card and a storage card IO capable of transferring patterns from tomes into the pattern storage card.

I understand C++ at an intermediate college level, making a GUI for you would be a great excuse to learn java. Which I have been putting off because I like working in C++ so much

**Comment by Mordenkainen** [comment]
Don't think I want to implement something like this
