### ISSUE TITLE
java.lang.NullPointerException 	at com.mordenkainen.equivalentenergistics.util.EMCCraftingPattern.relearnPatterns(EMCCraftingPattern.java:231) ~[EMCCraftingPattern.class:?] 

### ISSUE THREAD

**Issue by s1mples** [Mordenkainen/EquivalentEnergistics#53]
Error look like i cannot load saved game.
I have 2 saves: 1 creative and 2 survival. Load world 1 - all ok. Close&save world 1. try load world 2 - no luck. And start poping out subj error in log.

EquivalentEnergistics - 0.6 - 1.7.10.jar
Full log at https://www.sendspace.com/file/70c20c

**Comment by Mordenkainen** [comment]
You have some invalid item that is either unretievable from the list of transmutable items, or that is returning a null emc value.

The log does not tell me what item so beyond that I can't say much more.

Have you been mucking with EMC values from the admin cokmmands or a tweaker mod?

**Comment by s1mples** [comment]
>>Have you been mucking with EMC values from the admin cokmmands or a tweaker mod?
Im not. This is modpack "Project Ozone" from "Curse voice" launcher. May be modpack creator make some EMC changes.

**Comment by Mordenkainen** [comment]
Sounds like something is changing an EMC value early in the loading process. This triggers the NPE because the EMC system is not ready to provide the data needed to build the patterns, causing the crash. Then when you reload the world, the EMC change has already been made, so no error is thrown.

This may actually be a ProjectE issue. This mod is just responding to a message from ProjectE saying the EMC values have changed.Perhaps ProjectE is sending this event too soon and is not yet ready to provide the data that will be requested as a result of the event.

**Comment by Mordenkainen** [comment]
Closing this issue as the pattern system has been rewritten. The issue can be re-opened if it happens again.
