### ISSUE TITLE
[idea]: Equivalent Energistics with Matter overdrive support?

### ISSUE THREAD

**Issue by mariodk** [Mordenkainen/EquivalentEnergistics#57]
can matter overdrive have support for this mod?
since matter overdrive kinda also have a EMC feel to it but in form of matter plasma
and matter overdrive´s  is a mod if  Ae2 + a EMC type mod that use RF/T with Scifi themed got a baby (the "matter network" part of the mod):
http://simeon.co.vu/Mods/MatterOverdrive/matter-network/

sadly no redstone controll on it or connection to AE2 in the mod itself and no more updates for 1.7.10
so no way to automate/autocrafting via AE2 in any way
but the plasma is a fluid you can have in tanks

so maybe you can cook something up via mod dev. magic(lel) 
im thinking since the plasma is a fluid you will needing yours mod+AE2+matter overdrive+extracells(for fluid AE)

**Comment by Mordenkainen** [comment]
I can take a look and see if it can be supported.

But first I have to finish a bunch of bug fixes.

**Comment by Mordenkainen** [comment]
Looking at this I see a big gotcha. It looks like MO Replication has a chance of failure. AE wouldn't know how to deal with that.

**Comment by mariodk** [comment]
nice 
since i really want a way to connect my matter network with AE
and since matter network is kinda of a EMC type of mod im guessing you could do something like you did with EMC
not sure if it will make it easier that the EMC like thing in matteroverdrive is a fluid type (also why im thinking for make this to work prober might need extracells addon but idk)

**Comment by Mordenkainen** [comment]
AE has no way to deal with a crafting operation that may fail. I don't think this is something I would be able to do.

**Comment by mariodk** [comment]
:( 
not even if you do something so
if you request crafting for 10 diamonds

the wont stop requesting diamonds until you got 10 (if one of the diamond fails)
im sure there most be a way 
and that refined dust will be sent in drives or if you set it to a recycler

**Comment by Mordenkainen** [comment]
All of that behavior is controlled by AE itself. Also that type of behavior would make it impossible to know if you have enough plasma for a given crafting, because actually crafting the item may cost more than the "recipe" says.

**Comment by MaPePeR** [comment]
You could make it always consume the stochastic expected value when using AE, so removing the randomness, but keeping the same result for time against infinity.

**Comment by Mordenkainen** [comment]
But then I also have to replace the crafting mechanic, rather than leverage the inbuilt crafting mechanic of the mod (something I don't really have to worry about with PE or EE).

It's something I can look into, but it is kinda backburnered as it would probably require a fair amount of heavy lifting: Create a system that exposes plasma fluid as an item, a way to transfer/reuse the "pattern" system of MO, create a block to duplicate the MO crafting mechanic minus the chance of random failure, other things I'm sure I haven't thought of.

The exposing plasma as an item in particular is a bit of a trial, though it is possible. In the long term I want to create a framework that will allow anything to be exposed to the AE crafting system as an item, no matter what it actually is. This would allow better implementations of autocrafting for things like Extracells and Thaumic Energistics as well as things like this, or ChromaticCraft chroma, etc.

I am currently working on a POC for this for EMC. Exposing it to the system as an item, but don't actually store it using item storage cells.

**Comment by mariodk** [comment]
maybe we dont need to turn the plamsa into a item but just use the plasma itself?
but that would need ExtraCells mods but Most modpacks has that mod anyway Extracells kinda should merge with AE2 soon so we see those two togther so often in packs

**Comment by Mordenkainen** [comment]
AE doesnt know how to craft with anything other than items... If you want autocrafting to work properly, all inputs must be items.

**Comment by jozefjan** [comment]
Appears to be fixed in ProjectE-1.7.10-PE1.10.1

**Comment by Mordenkainen** [comment]
Lets leave this type of thing to another mod.
