### ISSUE TITLE
[Crash] java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by Thagus** [Mordenkainen/EquivalentEnergistics#59]
Hello, 

I'm getting IllegalAccessError whenever I try to place an EMC Assembler or an EMC condenser in the world. The following crash reports are the ones generated when I try to place the assembler or the condenser respectively:
http://pastebin.com/Y1VfYpNy
http://pastebin.com/2bicvynx

I'm using ProjectE and Applied Energistics 2 rv3. This error is only reproducible with AE2 rv3, there's no such problem with rv2. 

There is a plan to support AE2 rv3?

Thanks.

**Comment by Kratzwurst** [comment]
Yeah i have the same issue. i play actually the modpack project ozone and have all modification on the new release version/beta updated and than will i placed the emc condensor... than crash it my game:

http://pastebin.com/P0frz4xN

greets

**Comment by mikeskey** [comment]
I just did exactly the same thing. Fiance and I are playing FTB Inventions and I added this to the pack with a few other mods and it's caused it to crash literally as soon as I placed the condenser. I hope this is something that's an easy fix and an update in the near future because I sure would like to give this mod a try.

**Comment by Impulse1989** [comment]
Same issue here too. I sooo wish I could use this on my FTB Inventions server!

**Comment by Mordenkainen** [comment]
Downgrading to AE2 RV2 stable 9 will make that error go away for the time being.
