### ISSUE TITLE
Crafting too many items

### ISSUE THREAD

**Issue by Ar4093** [Mordenkainen/EquivalentEnergistics#75]
When crafting low-EMC items (somewhere between 10k and 100k EMC), the auto-crafting crafts a lot more items than requested. For example:

![image](https://user-images.githubusercontent.com/10649509/29525864-53c14696-8694-11e7-85a9-b7bd0dbfb8dd.png)

Trying to craft 1 Gold Ingot, I get this: 

![image](https://user-images.githubusercontent.com/10649509/29525896-6806bf64-8694-11e7-813b-5c72d1bc19df.png)

Even if I try to craft 2 Gold ingots (which exactly equals the EMC of one EMC Crystal, 4096), I get the same screen.

This gets better the higher EMC items I try to craft (8 Emeralds when requesting 1, and 1 per 1 Nether Star).

**Versions**:
Equivalent Energistics - 0.7
Forge - Newest for 1.7.10 (1614)
AE2 - rv3-beta6
ProjectE - 1.7.10-PE1.10.1
(Probably not relevant) NEI 1.0.5.120, CodeChickenCore 1.0.7.47

**Comment by Mordenkainen** [comment]
This is the expected behavior. The pattern system looks at the EMC value of an item and sets the pattern to craft a stack of the item up to a predefined value for a stack.

This is a config item "MaxEMCForAStack" and determines the target stack value. Once the EMC value of an item exceeds this, only a single item will be crafted by the pattern.

This was done to both increase the speed of autocrafting and reduce the amount of EMC temporarily wasted during crafting.

A somewhat artificial example would be, assuming you had changed cobbles emc value to 0.001....
Without this feature, asking for 1000 cobble would  take 350 seconds and consumes 1000 EMC worth of Crystals, returning 999 emc worth of crystals when complete. It also needs enough crafting CPU storage for 2000 items and 1000 crafting opperations.

With the feature, the same request takes 5.4 seconds, and consumes 16 EMC worth of Crystals, returning 15 EMC worth of Crystals when complete. This only needs CPU storage for 1015 items and 16 crafting operations, so can be done with a significantly smaller CPU.

**Comment by Mordenkainen** [comment]
I,z
