### ISSUE TITLE
Unable to select the number of items to craft

### ISSUE THREAD

**Issue by Dulo1997** [Mordenkainen/EquivalentEnergistics#80]
Each time I attempt to craft something using EMC it always crafts a full stack, I can't even specify if I want to craft one stack or multiple stacks. 
The issue is that I want to craft 2 diamonds for example and I have enough EMC for two diamonds but not for a full stack. 
Can this be fixed somehow? Can I fix it for myself somehow and what's causing this problem?

**Comment by Anyone700** [comment]
I strongly believe that this is an instance where the logic tree that supports the function discussed here: 
https://github.com/Mordenkainen/EquivalentEnergistics/issues/75
Was not written for the potential that crafting a whole stack may exceed the amount of EMC that the terminal has at it's disposal. It is easy for a programmer to overlook creating an upper bounding, when coding a logic tree to elicit a lower bounding.

However the fact that it does not allow you to craft over 64 of an item is perplexing. Especially when my download of the latest distribution does not exhibit this behavior.

A fix would be as simple as checking EMC required against available EMC after determining that it is more efficient to craft a whole stack vs a single item.

The fact that when you try to craft an item with a high enough EMC, it crafts the correct number of items supports this theory.

To determine the EMC requirement of an item to craft the correct number of items, I would need to see and understand the logic behind the function behind the above link.

However there is another dynamic to this issue that you have not mentioned and the above solution excludes, once you have a certain amount of EMC, and are crafting high EMC items, this problem no longer occors. This suggests that there is an upper bounding, just not one relative to EMC stored in the terminal. Perhaps it was mistakenly made relative to the largest EMC crystal in the network, or the storage capacity of the network.

**Comment by Mordenkainen** [comment]
This is the same issue as #75.

This is due to the optimizations applied to the autocrafting to reduce the number and scale of Crafting CPUs required.

By default it is configured to craft anything with an EMC below 131,072 in a stack of up to 131,072 EMC. This means that cobblestone, with an EMC value of 1 will craft in a stack of 64 (the max stack size), and Diamonds (8,192 EMC) will craft in a stack of 16 (131,072 / 8192). Anything over this value will craft as single items. If you want Diamonds to craft as a single item instead of a stack of 16, change the value "maxStackEMC" in the config file to 8192 or lower.

There are some downsides to reducing this value. There are certain circumstances that apply to items that craft individually:
- Crafting jobs for more than one item of these items will be slower
- Crafting jobs for more than one item of these items will consume more Crafting CPU storage and will require larger CPUs
- Crafting jobs for more than one item of these items will cost more AE power
- There may be more temporary loss of EMC Crystals to complete the crafting job (note that this mostly applies to EE3 since Project E does not have much that requires fractional EMC values)

As far as the idea of "adjusting" the output based on the amount of EMC in the network.... That simply isn't possible. AE does not allow "dynamic" recipes. Changing the number of items a recipe produces requires the whole network to relearn all recipes. If the change invalidates a crafting job that is already pending (like changing the stack size of something from 32 to 16, when a crafting job has already calculated it's requirements around the 32 stack size) then that crafting job will hang forever. This also poses even more issues during the simulation phase of crafting, where items are only virtually removed from the network for simulation, causing the simulated stack sizes to differ from the actual stack sizes once the crafting job actually begins. (Note that all of this is controlled by AE's autocrafting system and is outside of the control of this mod)

A longer term solution is to add a terminal that gives the user control over the output stack size of all recipes. But that still carries the downside that it will invalidate any active crafting when a stacksize changes.
