### ISSUE TITLE
Automated addition of EMC recipies

### ISSUE THREAD

**Issue by Anyone700** [Mordenkainen/EquivalentEnergistics#82]
If I plop a new item into my condenser without popping it into my tablet. Poof, its gone. Now I have to craft that recipe all over again. This is inconvenient, and could be solved by having a block that goes between a block with an inventory and the condenser. It should be expensive, but it would make this mod so much better.

When grabbing items from a tablet, the process is instantaneous, and you have complete control of the number of items you are grabbing. You can also instantly input EMC items without having to worry about putting it in the correct input(terminal vs condenser linked chest). Due to these facts, this add-on is FAR outclassed by the tablet when it comes to crafting.

The only thing this mod really brings to the table is no longer hard-code dirt-simple operations into an auto-crafter. While this is extreemely useful, this add-on has FAR more potential.

If you introduce an interface that can add recipes to networked tomes and condense EMC with networked condensers. That also makes it so that you can pull items in the same way as a tablet, however it would be best in my opinion that the instant nature of a tablet was left to a far more resource costly version of the interface, much like your condensers/crafters. Then this add-on will be far better

**Comment by Mordenkainen** [comment]
So it sounds like there are several suggestions here... Lets address them one at a time:

- Something that will "auto-learn" new transmutaions when encountering an unknown item:
Just like with Project E, if the player forgets to learn a new item into their tablet it doesn't get added to their transmutations. Also, since the network could have multiple tomes linked to it, it would have no way of knowing which tome to add it to. Adding it to all players tomes seems excessive and breaks the Project E progression.

- Control over crafting amount, tablet is faster:
For both of these you can argue that the same applies between normal crafting and ME autocrafting. Normal crafting is instantaneous, ME autocrafting takes time. Normal crafting can craft up to a stack at a time, ME crafts a "single crafting" of an item at a time. (this is a case where the EMC Assembler differs because it tries to optimize the stack counts to reduce the load on the crafting CPUs)

The system has been designed to try to maintain parity between what Project E and AE2 do. It is not intended to replace or change the behavior of either. There is a price to be paid for the automation of crafting.

- An interface that can import and export EMC items:
The condenser is your EMC importer. It is up to the player to ensure that only items that they want converted to EMC are put into it. A future enhancement already on the list is a sorter that will identify items a player has not already learned and shunt them off to another inventory rather than condensing them.

As far as exporting EMC items.... Both the export bus and the interface from Vanilla AE are capable of this by adding a crafting card.

- "You can also instantly input EMC items without having to worry about putting it in the correct input(terminal vs condenser linked chest)"
This is something that has been discussed before. Having items input into the terminal automatically converted to EMC is not something I will do. There is too much potential for a person to accidentally put their "Super Awesome Sword Mk 2000000" into the terminal only to have it insta-converted to EMC.

- "Due to these facts, this add-on is FAR outclassed by the tablet when it comes to crafting." & "The only thing this mod really brings to the table is no longer hard-code dirt-simple operations into an auto-crafter."
We will just have to disagree on this one. Without this mod, there is no possibility of crafting with EMC at all. Also, since many mod added items have EMC, including items that would require furnaces, pulverizers, and/or other custom crafting steps to make, I don't believe that it is only "dirt-simple" recipes it saves you from adding. It can save you from having to add complete processing sections to your ME network, so I would have to disagree with the latter statement.  As far as the former, consider when you want to start a crafting job that needs 10,000,000 cobble and think about having to make that cobble on the tablet then carry it to your ME terminal. So you can carry 10,000,000 cobble back and forth, or you can click a couple of buttons....

**Comment by Anyone700** [comment]
I dont think you quite understand what I'm trying to say due to the often ham-fisted nature of my writing. Though, due to your reply I believe I can rephrase what I'm trying to communicate so you can understand what I am trying to say.

It seems without rephrasing, we already agree that the tablet and the network both have their place. However in my writing I was too hard on the mod to communicate what I meant.

I believe this will better communicate my ideas than my original approach

-I want to use my networked EMC resources in my tablet

-I want to have EMC from my tablet automatically added to my network

-I want a way to update my tome without using a turtle

The only place where I see that I communicated properly and we have a clear disagreement is "Adding it to all players tomes seems excessive and breaks the Project E progression." a player could simply pull the item they want from the terminal and plop it into your tablet.

If you want me to create a free in-depth and quality tutorial to aid in preventing stupid questions with easy answers like this: 
As far as exporting EMC items.... Both the export bus and the interface from Vanilla AE are capable of this by adding a crafting card.

Simply email me an FAQ and I will put 20-40 hours of my time into making a quality production. I have worked with developers before and I enjoy making good tutorials for great code. Check Anyone700 on youtube if you want to see some examples of my work with RoKo0 and DCR3D (recently renamed to "Dream car builder").

**Comment by Mordenkainen** [comment]
So I think you may have a misunderstanding about how the transmutation tablet works under the covers.

EMC is not stored in the tablet. It is stored in the player. If two players are looking at the same tablet at the same time, they will see different values, because the tablet is actually showing the EMC stored in the player, not the tablet.

In addition, the tablet does not expose the amount of EMC the player(s) looking at it has.

Because of this, it is not possible to link the EMC in the tablet into the ME network, and vice versa.

The condenser IS aware of EMC storage though. So if you fill your tablet with EMC, you can then put that EMC into a Klein Star, and feed the Klein Star into a condenser. The EMC stored in the Star will be imported to your network.

Coming in the next version is the ability to use an EMC Storage Cell in the tablet instead of a Klein Star.

As far as using a turtle for the tome.... I'm not sure what you are talking about. If you mean you have to remove and replace the tome, the tome should live update when you learn new transmutations. If it doesn't that would probably be an issue with Project E. Project E posts an event when the player learns or forgets a transmutation, and the assemblers listen for that event and rebuild their recipes when they get it. If the tome is not updating live, that probably means Project E is not posting the event.

As far as the point you agree we disagree on... Well, you make an assumption that there is no security terminal preventing that player from removing an item from your terminal. While you are correct that it may be trivial for a player to do that, it is no more or less trivial than that player asking you to make one of those items and toss it on the ground so they can learn it. Again, this is maintaining parity with the Project E progression.

Finally, You may need to rethink what the mod is actually doing. It is allowing you to add crafting recipes to your ME network that use EMC instead of items as input. This means that once the recipe is added, it is a normal ME recipe in all respects (in fact they become item based recipes). The ME network has no idea that the EMC recipes are any different than a standard item based one. Because of this, all basic ME functionality that relates to crafting applies. This includes using Crafting Cards in Buses, Interfaces, and Level Emitters, as well as the crafting system being able to use an EMC recipe to make an ingredient for a standard crafting recipe during autocrafting.

Also, I appreciate the offer of the tutorial, and I may touch base when the new version is released. Thanks!

**Comment by b52src** [comment]
+1 I would also like to to see the ability to auto add unlearned Items not in the system, perhaps allowing the condenser to connect directly to a transmutation table (similar to how Refined Storage dose with a storage bus on the table) and route unlearned items with EMC up to the tablet and other items without MC routed to other connected storage like the condenser currently allows.

**Comment by Mordenkainen** [comment]
A way to filter unknown items will be provided with the sorter
